#端口配置
server:
  port: 8080

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meta_sql
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml