#端口配置
server:
  port: 8080

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.96.214:3306/meta_sql?allowMultiQueries=true
    username: root
    password: Hlxd@123

mybatis:
  mapper-locations: classpath:mapper/*.xml